version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: flask-backend
    networks:
      - flask-network
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: flask-frontend
    networks:
      - flask-network
    ports:
      - "5001:5001"
    depends_on:
      - backend

networks:
  flask-network:
    driver: bridge
